pipeline {
    agent any
 
    tools {nodejs "node"}
 
    stages {
 
        stage('Cypress Parallel Test Suite') {
            parallel {
                stage('Slave 1') {
                    agent {
                        label "Agent_1"
                    }
                    steps {
                        git url: 'https://github.com/anafernandez9217/Cypress_curso_1.git'
                        bat 'npm install'
                        bat 'npm update'                       
                        bat 'npx cypress run cypress run --record --key 4c3a3488-d778-4a8c-b301-adb62be8c726  --parallel'
                    
                    }
                }
 
                stage('Slave 2') {
                    agent {
                        label "Agent_2"
                    }
                    steps {
                        git url: 'https://github.com/anafernandez9217/Cypress_curso_1.git'
                        bat 'npm install'
                        bat 'npm update'                       
                        bat 'npx cypress run cypress run --record --key 4c3a3488-d778-4a8c-b301-adb62be8c726  --parallel'
                    
                    }
                }
 
                stage('Slave 3') {
                    agent {
                        label "Agent_3"
                    }
                    steps {
                        git url: 'https://github.com/anafernandez9217/Cypress_curso_1.git'
                        bat 'npm install'
                        bat 'npm update'                       
                        bat 'npx cypress run cypress run --record --key 4c3a3488-d778-4a8c-b301-adb62be8c726  --parallel'
                    
                    }
                }
 
                stage('Slave 4') {
                    agent {
                        label "Agent_4"
                    }
                    steps {
                        git url: 'https://github.com/anafernandez9217/Cypress_curso_1.git'
                        bat 'npm install'
                        bat 'npm update'                       
                        bat 'npx cypress run cypress run --record --key 4c3a3488-d778-4a8c-b301-adb62be8c726  --parallel'
                    
                    }
                }
 
               
 
                
   
                  
            }
 
             
        }
 
    }
            
}